-- Source Appian CDT: AS_IO_V_OnboardingFundingDateChanges
-- Description: The data type for the attributes related to the view for the onboarding funding date changes
DROP VIEW IF EXISTS AS_IO_V_ONBOARDING_FUNDING_DATE_CHANGES CASCADE;
CREATE VIEW AS_IO_V_ONBOARDING_FUNDING_DATE_CHANGES AS
SELECT
    NULL::INT AS FUNDING_DETAILS_AUDIT_FIELD_ID,
    NULL::INT AS FUNDING_DETAILS_AUDIT_ID,
    NULL::INT AS REQUEST_ID,
    NULL::VARCHAR(255) AS REQUEST_NAME,
    NULL::VARCHAR(255) AS TYPE,
    NULL::VARCHAR(255) AS OLD_FUNDING_DATE,
    NULL::VARCHAR(255) AS NEW_FUNDING_DATE,
    NULL::VARCHAR(255) AS PRIMARY_OWNER,
    NULL::INT AS CUSTOMER_ID,
    NULL::VARCHAR(255) AS CUSTOMER_NAME,
    NULL::VARCHAR(255) AS REASON,
    NULL::DATE AS ONB_CREATED_DATE,
    NULL::TIMESTAMP AS TIMESTAMP,
    NULL::VARCHAR(255) AS REGION_CODE,
    NULL::DATE AS ACTUAL_FUNDING_DATE,
    NULL::DATE AS ESTIMATED_FUNDING_DATE
;
-- NOTE: View definition requires manual review to add proper source tables and joins
