-- Source Appian CDT: AS_IO_V_OnboardingRequest
-- Description: Data type for the attributes related to the view for the onboarding request record
DROP VIEW IF EXISTS AS_IO_V_ONBOARDING_REQUEST CASCADE;
CREATE VIEW AS_IO_V_ONBOARDING_REQUEST AS
SELECT
    NULL::INT AS REQUEST_ID,
    NULL::VARCHAR(255) AS UNIQUE_IDENTIFIER,
    NULL::VARCHAR(255) AS STATUS,
    NULL::VARCHAR(255) AS TYPE,
    NULL::DATE AS EST_FUNDING_DATE,
    NULL::DOUBLE PRECISION AS EST_FUNDING_VALUE,
    NULL::VARCHAR(255) AS EST_VALUE_CURRENCY_CODE,
    NULL::DATE AS ACTUAL_FUNDING_DATE,
    NULL::DOUBLE PRECISION AS ACTUAL_FUNDING_VALUE,
    NULL::VARCHAR(255) AS ACTUAL_VALUE_CURRENCY_CODE,
    NULL::DATE AS COALESCED_FUNDING_DATE,
    NULL::DOUBLE PRECISION AS COALESCED_FUNDING_VALUE,
    NULL::VARCHAR(255) AS COALESCED_VALUE_CURRENCY_CODE,
    NULL::VARCHAR(255) AS PRIORITY_CODE,
    NULL::BOOLEAN AS FOR_NEW_CLIENT,
    NULL::DATE AS CREATED_DATE,
    NULL::TIMESTAMP AS MODIFIED_DATETIME,
    NULL::INT AS CUSTOMER_ID,
    NULL::BOOLEAN AS IS_AT_RISK,
    NULL::INT AS PRIMARY_OWNER_ID
;
-- NOTE: View definition requires manual review to add proper source tables and joins
