-- Source Appian CDT: AS_IO_V_CompletedOnboarding
-- Description: Data type for the attributes related to the view for the complete onboardings for metrics
DROP VIEW IF EXISTS AS_IO_V_COMPLETED_ONBOARDING_REQUEST CASCADE;
CREATE VIEW AS_IO_V_COMPLETED_ONBOARDING_REQUEST AS
SELECT
    NULL::INT AS REQUEST_ID,
    NULL::VARCHAR(255) AS UNIQUE_IDENTIFIER,
    NULL::VARCHAR(255) AS TYPE,
    NULL::DATE AS EST_FUNDING_DATE,
    NULL::DATE AS ACTUAL_FUNDING_DATE,
    NULL::VARCHAR(255) AS REGION_CODE,
    NULL::INT AS YEAR,
    NULL::INT AS QUARTER,
    NULL::INT AS COMPLETION_DAYS,
    NULL::VARCHAR(255) AS PRIMARY_OWNER,
    NULL::INT AS MONTH,
    NULL::DATE AS CREATED_DATE,
    NULL::DATE AS MODIFIED_DATE,
    NULL::VARCHAR(255) AS FUNDING_DATE_STATUS,
    NULL::VARCHAR(255) AS CUSTOMER_NAME
;
-- NOTE: View definition requires manual review to add proper source tables and joins
