-- Source Appian CDT: AS_IO_V_TaskCompletionType
-- Description: Data type for the attributes related to the view for the Task Completion Type
DROP VIEW IF EXISTS AS_IO_V_TASK_COMPLETION_TYPE CASCADE;
CREATE VIEW AS_IO_V_TASK_COMPLETION_TYPE AS
SELECT
    NULL::INT AS TASK_ID,
    NULL::VARCHAR(255) AS TASK_NAME,
    NULL::VARCHAR(255) AS CUSTOMER_NAME,
    NULL::DATE AS CREATED_DATE,
    NULL::INT AS GROUP_ASSIGNEE,
    NULL::VARCHAR(255) AS COMPLETED_BY,
    NULL::DATE AS DUE_DATE,
    NULL::DATE AS COMPLETED_DATE,
    NULL::VARCHAR(255) AS COMPLETION_TYPE,
    NULL::INT AS REQUEST_ID,
    NULL::VARCHAR(255) AS TEMPLATE_NAME,
    NULL::VARCHAR(255) AS CATEGORY_NAME,
    NULL::VARCHAR(255) AS UNIQUE_IDENTIFIER,
    NULL::VARCHAR(255) AS ONBOARDING_TYPE
;
-- NOTE: View definition requires manual review to add proper source tables and joins
