-- Source Appian CDT: AS_IO_V_ChangesToTaskDueDate
-- Description: View is for changes to task due date
DROP VIEW IF EXISTS AS_IO_V_CHANGES_TO_TASK_DUE_DATES CASCADE;
CREATE VIEW AS_IO_V_CHANGES_TO_TASK_DUE_DATES AS
SELECT
    NULL::INT AS TASK_ACTION_AUDIT_ID,
    NULL::INT AS TASK_ID,
    NULL::VARCHAR(255) AS TASK_NAME,
    NULL::INT AS GROUP_ASSIGNEE,
    NULL::VARCHAR(255) AS ASSIGNEE,
    NULL::DATE AS OLD_DUE_DATE,
    NULL::DATE AS NEW_DUE_DATE,
    NULL::VARCHAR(255) AS CUSTOMER_NAME,
    NULL::INT AS TASK_CATEGORY_ID,
    NULL::VARCHAR(255) AS COMPLETED_BY,
    NULL::DATE AS COMPLETED_DATE,
    NULL::TIMESTAMP AS TIMESTAMP,
    NULL::INT AS REQUEST_ID,
    NULL::VARCHAR(255) AS REASON,
    NULL::VARCHAR(255) AS UNIQUE_IDENTIFIER,
    NULL::DATE AS ONBOARDING_CREATED_DATE,
    NULL::DATE AS DATESTAMP,
    NULL::VARCHAR(255) AS ONBOARDING_TYPE,
    NULL::VARCHAR(255) AS MODIFIED_BY
;
-- NOTE: View definition requires manual review to add proper source tables and joins
