-- Source Appian CDT: AS_IO_V_RequestWithOwner
-- Description: Data type for the attributes related to the view for joining onboarding request record with owners
DROP VIEW IF EXISTS AS_IO_V_REQUEST_WITH_OWNER CASCADE;
CREATE VIEW AS_IO_V_REQUEST_WITH_OWNER AS
SELECT
    NULL::INT AS REQUEST_ID,
    NULL::INT AS OWNER_ID,
    NULL::VARCHAR(255) AS UNIQUE_IDENTIFIER,
    NULL::VARCHAR(255) AS OWNER,
    NULL::VARCHAR(255) AS PRIMARY_OWNER,
    NULL::VARCHAR(255) AS STATUS,
    NULL::DATE AS EST_FUNDING_DATE,
    NULL::DOUBLE PRECISION AS EST_FUNDING_VALUE,
    NULL::DATE AS ACTUAL_FUNDING_DATE,
    NULL::DOUBLE PRECISION AS ACTUAL_FUNDING_VALUE,
    NULL::VARCHAR(255) AS TYPE,
    NULL::VARCHAR(255) AS PRIORITY_CODE,
    NULL::DATE AS CREATED_DATE,
    NULL::INT AS CUSTOMER_ID,
    NULL::BOOLEAN AS IS_AT_RISK
;
-- NOTE: View definition requires manual review to add proper source tables and joins
