-- Source Appian CDT: AS_IO_V_Account
-- Description: Record View of Account with locales
DROP VIEW IF EXISTS AS_IO_V_ACCOUNT CASCADE;
CREATE VIEW AS_IO_V_ACCOUNT AS
SELECT
    NULL::INT AS ACCOUNT_ID,
    NULL::VARCHAR(255) AS ACCOUNT_NAME,
    NULL::VARCHAR(255) AS TYPE,
    NULL::DATE AS EST_FUNDING_DATE,
    NULL::DATE AS ACTUAL_FUNDING_DATE,
    NULL::TIMESTAMP AS CREATED_DATETIME,
    NULL::TIMESTAMP AS MODIFIED_DATETIME,
    NULL::BOOLEAN AS IS_PARENT,
    NULL::BOOLEAN AS IS_DELETED,
    NULL::INT AS REQUEST_ID
;
-- NOTE: View definition requires manual review to add proper source tables and joins
