-- Source Appian CDT: AS_ALT_AlertArgument
-- Description: Arguments for internationalization of alert messages
DROP TABLE IF EXISTS AS_ALT_ALERT_ARGUMENT CASCADE;
CREATE TABLE AS_ALT_ALERT_ARGUMENT (
    ALERT_ARGUMENT_ID INT PRIMARY KEY,
    ARGUMENT_POSITION INT,
    ARGUMENT VARCHAR(255),
    ARGUMENT_DISPLAY_TYPE VARCHAR(255)
);
