-- Source Appian CDT: AS_ALT_V_AlertDismissalStatus
-- Description: Data type for the attributes related to the view AS_ALT_ALERT_DISMISSAL_STATUS
DROP TABLE IF EXISTS AS_ALT_ALERT_DISMISSAL_STATUS CASCADE;
CREATE TABLE AS_ALT_ALERT_DISMISSAL_STATUS (
    ALERT_ID INT PRIMARY KEY,
    ALERT_SET_ID INT,
    MESSAGE VARCHAR(255),
    I18N_FOLDER_ID INT,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    I18N_BUNDLE_NAME VARCHAR(255),
    ALERT_DISMISSAL_ID INT,
    DISMISSAL_REASON INT,
    DISMISSAL_COMMENT VARCHAR(255),
    DISMISSED_BY VARCHAR(255),
    DISMISSED_ON TIMESTAMP
);
