-- Source Appian CDT: AS_EI_NORTHROW_COMPANY_CHECK_REFRESH_INTERVAL
-- Description: Created to update refresh interval
DROP TABLE IF EXISTS AS_EI_NORTHROW_COMPANY_CHECK_REFRESH_INTERVAL CASCADE;
CREATE TABLE AS_EI_NORTHROW_COMPANY_CHECK_REFRESH_INTERVAL (
    ID INT PRIMARY KEY,
    COMPANY_ID INT,
    REFRESH_INTERVAL_DAYS INT,
    IS_ACTIVE BOOLEAN,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
