-- Source Appian CDT: AS_EI_NORTHROW_CompanyCheckSummary
-- Description: refers to AS_EI_COMPANY_CHECK_SUMMARY entity fields
DROP TABLE IF EXISTS AS_EI_NORTHROW_COMPANY_CHECK_SUMMARY CASCADE;
CREATE TABLE AS_EI_NORTHROW_COMPANY_CHECK_SUMMARY (
    ID INT PRIMARY KEY,
    CHECK_UUID VARCHAR(255),
    COMPANY_ID INT,
    JSON_RESPONSE VARCHAR(255),
    STATUS VARCHAR(255),
    IS_SUCCESS BOOLEAN,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
