-- Source Appian CDT: AS_EI_NORTHROW_Alerts
-- Description: refers to AS_EI_NORTHROW_ALERTS entity fields
DROP TABLE IF EXISTS AS_EI_NORTHROW_ALERTS CASCADE;
CREATE TABLE AS_EI_NORTHROW_ALERTS (
    ID INT PRIMARY KEY,
    CRID VARCHAR(255),
    COMPANY_ID INT,
    PERSON_ID INT,
    CATEGORY VARCHAR(255),
    MESSAGE VARCHAR(255),
    SCORE INT,
    TYPE VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
