-- Source Appian CDT: AS_EI_CHS_CompanyProfile
-- Description: refers to AS_EI_CHS_COMPANY_PROFILE entity fields
DROP TABLE IF EXISTS AS_EI_CHS_COMPANY_PROFILE CASCADE;
CREATE TABLE AS_EI_CHS_COMPANY_PROFILE (
    COMPANY_PROFILE_ID INT PRIMARY KEY,
    COMPANY_ID INT,
    JSON_RESPONSE VARCHAR(255),
    STATUS VARCHAR(255),
    IS_SUCCESS BOOLEAN,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
