-- Source Appian CDT: AS_EI_DNB_UltimateBeneficialOwnership
-- Description: refers to AS_EI_DNB_ULTIMATE_BENEFICIAL_OWNERSHIP  entity fields
DROP TABLE IF EXISTS AS_EI_DNB_ULTIMATE_BENEFICIAL_OWNERSHIP CASCADE;
CREATE TABLE AS_EI_DNB_ULTIMATE_BENEFICIAL_OWNERSHIP (
    ULTIMATE_BENEFICIAL_OWNERSHIP _ID INT PRIMARY KEY,
    COMPANY_ID INT,
    API_VERSION VARCHAR(255),
    JSON_RESPONSE VARCHAR(255),
    STATUS VARCHAR(255),
    IS_SUCCESS BOOLEAN,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
