-- Source Appian CDT: AS_EI_DNB_SanctionsWatchlist
-- Description: refers to AS_EI_DNB_SANCTIONS_WATCHLIST entity fields
DROP TABLE IF EXISTS AS_EI_DNB_SANCTIONS_WATCHLIST CASCADE;
CREATE TABLE AS_EI_DNB_SANCTIONS_WATCHLIST (
    SANCTIONS_WATCHLIST_ID INT PRIMARY KEY,
    COMPANY_ID INT,
    API_VERSION VARCHAR(255),
    JSON_RESPONSE VARCHAR(255),
    STATUS VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
