-- Source Appian CDT: AS_FS_CustomerDocument
-- Description: Data type for a document associated with a customer
DROP TABLE IF EXISTS AS_FS_CUSTOMER_DOCUMENT CASCADE;
CREATE TABLE AS_FS_CUSTOMER_DOCUMENT (
    CUSTOMER_DOCUMENT_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    APPIAN_DOC_ID INT,
    FOLDER_ID INT,
    DOCUMENT_NAME VARCHAR(255),
    DOCUMENT_DESC VARCHAR(255),
    DOC_TYPE_CODE VARCHAR(255),
    FILE_TYPE VARCHAR(255),
    EXPIRATION_DATE DATE,
    IS_DELETED BOOLEAN,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    IS_INTERNAL BOOLEAN,
    IS_UPLOADED_BY_CUSTOMER BOOLEAN
);
