-- Source Appian CDT: AS_FS_R_GlobalIndustryClass
-- Description: Global Industry Classification Reference Table
DROP TABLE IF EXISTS AS_FS_R_GLOBAL_INDUSTRY_CLASS CASCADE;
CREATE TABLE AS_FS_R_GLOBAL_INDUSTRY_CLASS (
    GBL_INDUSTRY_CLASS_ID INT PRIMARY KEY,
    CLASS_NAME VARCHAR(255),
    CLASS_CODE VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    SORT_ORDER INT
);
