-- Source Appian CDT: AS_FS_ALT_A_AlertConfigurationTriggerSet
-- Description: Audit table for alert configuration trigger
DROP TABLE IF EXISTS AS_FS_ALT_A_ALERT_CONFIGURATION_TRIGGER_SET CASCADE;
CREATE TABLE AS_FS_ALT_A_ALERT_CONFIGURATION_TRIGGER_SET (
    ALERT_CONFIGURATION_TRIGGER_SET_AUDIT_ID INT PRIMARY KEY,
    ALERT_CONFIGURATION_TRIGGER_SET_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
