-- Source Appian CDT: AS_FS_ALT_CONF_AlertConfigurationEvent
-- Description: AlertConfigurationEvent Datatype for AS_FS
DROP TABLE IF EXISTS AS_FS_ALT_CONF_ALERT_CONFIGURATION_EVENT CASCADE;
CREATE TABLE AS_FS_ALT_CONF_ALERT_CONFIGURATION_EVENT (
    ALERT_CONFIGURATION_EVENT_ID INT PRIMARY KEY,
    ALERT_CONFIGURATION_ID INT,
    EVENT_TYPE_CODE VARCHAR(255),
    EVENT_TYPE_SPECIFIC_FIELDS_JSON VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
