-- Source Appian CDT: AS_FS_BeneficialOwner
-- Description: CDT containing information about customer beneficial owners
DROP TABLE IF EXISTS AS_FS_BENEFICIAL_OWNER CASCADE;
CREATE TABLE AS_FS_BENEFICIAL_OWNER (
    BENEFICIAL_OWNER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    NAME VARCHAR(255),
    BENEFICIAL_OWNERSHIP_TYPE_CODE VARCHAR(255),
    BENEFICIAL_OWNERSHIP_PERCENT DECIMAL(18,4),
    EIN VARCHAR(255),
    IS_FROM_DNB BOOLEAN,
    IS_ACTIVE BOOLEAN,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
