-- Source Appian CDT: AS_FS_Account
-- Description: Child CDT for the Account Record -- This is nested under AS_FS_Product
DROP TABLE IF EXISTS AS_FS_ACCOUNT CASCADE;
CREATE TABLE AS_FS_ACCOUNT (
    ACCOUNT_ID INT PRIMARY KEY,
    PRODUCT_ID INT,
    NAME VARCHAR(255),
    TYPE VARCHAR(255),
    ACCOUNT_NUMBER VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    IS_PARENT BOOLEAN,
    IS_DELETED BOOLEAN
);
