-- Source Appian CDT: AS_FS_A_AllUserSettingsField
-- Description: Audit CDT for AlluserSettings Table
DROP TABLE IF EXISTS AS_FS_A_R_ALL_USER_SETTINGS_FIELD CASCADE;
CREATE TABLE AS_FS_A_R_ALL_USER_SETTINGS_FIELD (
    USER_SETTINGS_AUDIT_FIELD_ID INT PRIMARY KEY,
    USER_SETTINGS_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
