-- Source Appian CDT: AS_FS_PayThreshold
-- Description: payment threshold information for a product or account
DROP TABLE IF EXISTS AS_FS_PAY_THRESHOLD CASCADE;
CREATE TABLE AS_FS_PAY_THRESHOLD (
    PAY_THRESHOLD_ID INT PRIMARY KEY,
    PRODUCT_ID INT,
    OPERATOR VARCHAR(255),
    THRESHOLD DOUBLE PRECISION,
    THRESHOLD_CURRENCY_CODE VARCHAR(255),
    AUTHORIZATIONS INT
);
