-- Source Appian CDT: AS_FS_A_Contact
-- Description: Holds auditing data for `AS_FS_Contact`
DROP TABLE IF EXISTS AS_FS_A_CONTACT CASCADE;
CREATE TABLE AS_FS_A_CONTACT (
    CONTACT_AUDIT_ID INT PRIMARY KEY,
    CONTACT_ID INT,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
