-- Source Appian CDT: AS_FS_A_Phone
-- Description: Holds auditing data for `AS_FS_Phone`
DROP TABLE IF EXISTS AS_FS_A_PHONE CASCADE;
CREATE TABLE AS_FS_A_PHONE (
    PHONE_AUDIT_ID INT PRIMARY KEY,
    CONTACT_AUDIT_ID INT,
    PHONE_ID INT,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
