-- Source Appian CDT: AS_FS_IDP_DocTypeZip
-- Description: Contains the fields of Doctype Zip file details
DROP TABLE IF EXISTS AS_FS_IDP_DOC_TYPE_ZIP CASCADE;
CREATE TABLE AS_FS_IDP_DOC_TYPE_ZIP (
    DOC_TYPE_ZIP_ID INT PRIMARY KEY,
    DOC_TYPE_ID INT,
    docTypeName VARCHAR(255),
    ZIP_ID INT,
    UPLOADED_BY VARCHAR(255),
    UPLOADED_ON TIMESTAMP,
    IS_TRAINING_SUCCESSFUL BOOLEAN
);
