-- Source Appian CDT: AS_FS_CHS_CompanyDetails
-- Description: refers to AS_FS_CHS_COMPANY_DETAILS entity fields
DROP TABLE IF EXISTS AS_FS_CHS_COMPANY_DETAILS CASCADE;
CREATE TABLE AS_FS_CHS_COMPANY_DETAILS (
    COMPANY_DETAILS_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    DATE_OF_CREATION DATE,
    EXTERNAL_REGISTRATION_NUMBER VARCHAR(255),
    JURISDICTION VARCHAR(255),
    CLASS VARCHAR(255),
    SUBCLASS VARCHAR(255),
    COMPANY_STATUS VARCHAR(255),
    COMPANY_STATUS_DETAIL VARCHAR(255),
    COMPANY_LINK_ID INT,
    FOREIGN_COMPANY_DETAILS_ID INT,
    ADDRESS_ID INT,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
