-- Source Appian CDT: AS_FS_A_Customer
-- Description: Holds auditing data for `AS_FS_Customer`
DROP TABLE IF EXISTS AS_FS_A_CUSTOMER CASCADE;
CREATE TABLE AS_FS_A_CUSTOMER (
    CUSTOMER_AUDIT_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
