-- Source Appian CDT: AS_FS_Term
-- Description: Data type for account terms
DROP TABLE IF EXISTS AS_FS_TERM CASCADE;
CREATE TABLE AS_FS_TERM (
    TERM_ID INT PRIMARY KEY,
    PERFORMANCE_START_DATE DATE,
    PERFORMANCE_RETURN_TERM INT,
    COMMITTED_MARGIN INT,
    RATE_LOCK INT,
    SHORT_LOCK INT,
    OTHER_TERM VARCHAR(255),
    IS_DELETED BOOLEAN
);
