-- Source Appian CDT: AS_FS_Phone
-- Description: Phone number information in FS namespace
DROP TABLE IF EXISTS AS_FS_PHONE CASCADE;
CREATE TABLE AS_FS_PHONE (
    PHONE_ID INT PRIMARY KEY,
    CONTACT_ID INT,
    CUSTOMER_ID INT,
    PHONE_TYPE VARCHAR(255),
    PHONE_COUNTRY_CODE VARCHAR(255),
    PHONE_NUMBER VARCHAR(255),
    EXTENSION VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
