-- Source Appian CDT: AS_FS_Address
-- Description: Address for a record in FS namespace
DROP TABLE IF EXISTS AS_FS_ADDRESS CASCADE;
CREATE TABLE AS_FS_ADDRESS (
    ADDRESS_ID INT PRIMARY KEY,
    CONTACT_ID INT,
    CUSTOMER_ID INT,
    ADDRESS_TYPE VARCHAR(255),
    STREET_ADDRESS VARCHAR(255),
    ADDRESS_LINE_2 VARCHAR(255),
    CITY VARCHAR(255),
    STATE_REGION VARCHAR(255),
    COUNTRY_CODE VARCHAR(255),
    POSTAL_CODE VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
