-- Source Appian CDT: AS_FS_A_Fee
-- Description: Data type refers to the attributes related to the Fee audit
DROP TABLE IF EXISTS AS_FS_A_FEE CASCADE;
CREATE TABLE AS_FS_A_FEE (
    FEE_AUDIT_ID INT PRIMARY KEY,
    FEE_ID INT,
    PRODUCT_AUDIT_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255),
    COUNTRY_AUDIT_ID INT
);
