-- Source Appian CDT: AS_FS_A_Customer_Field
-- Description: Holds auditing data for `AS_FS_Customer` - simple field change
DROP TABLE IF EXISTS AS_FS_A_CUSTOMER_FIELD CASCADE;
CREATE TABLE AS_FS_A_CUSTOMER_FIELD (
    CUSTOMER_AUDIT_FIELD_ID INT PRIMARY KEY,
    CUSTOMER_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
