-- Source Appian CDT: AS_FS_A_Pay_Threshold_Field
-- Description: Data type refers to the attributes related to the pay threshold fields
DROP TABLE IF EXISTS AS_FS_A_PAY_THRESHOLD_FIELD CASCADE;
CREATE TABLE AS_FS_A_PAY_THRESHOLD_FIELD (
    PAY_THRESHOLD_AUDIT_FIELD_ID INT PRIMARY KEY,
    PAY_THRESHOLD_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
