-- Source Appian CDT: AS_FS_AllUserSettings
DROP TABLE IF EXISTS AS_FS_R_ALL_USER_SETTINGS CASCADE;
CREATE TABLE AS_FS_R_ALL_USER_SETTINGS (
    USER_SETTING_ID INT PRIMARY KEY,
    USER_SETTING_CODE VARCHAR(255),
    USER_SETTING_VALUE VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
