-- Source Appian CDT: AS_FS_ALT_A_AlertConfigurationTriggerConditionField
-- Description: CDT for alert configuration trigger condition fields
DROP TABLE IF EXISTS AS_FS_ALT_A_ALERT_CONFIGURATION_TRIGGER_CONDITION_FIELD CASCADE;
CREATE TABLE AS_FS_ALT_A_ALERT_CONFIGURATION_TRIGGER_CONDITION_FIELD (
    ALERT_CONFIGURATION_TRIGGER_CONDITION_FIELD_ID INT PRIMARY KEY,
    ALERT_CONFIGURATION_TRIGGER_CONDITION_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
