-- Source Appian CDT: AS_FS_A_CustomerRelation_Field
-- Description: Holds auditing data for `AS_FS_CustomerRelation` - simple field change
DROP TABLE IF EXISTS AS_FS_A_CUSTOMER_RELATION_FIELD CASCADE;
CREATE TABLE AS_FS_A_CUSTOMER_RELATION_FIELD (
    CUSTOMER_RELATION_AUDIT_FIELD_ID INT PRIMARY KEY,
    CUSTOMER_RELATION_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
