-- Source Appian CDT: AS_FS_CHS_CompanyLink
-- Description: refers to AS_FS_CHS_COMPANY_LINK entity fields
DROP TABLE IF EXISTS AS_FS_CHS_COMPANY_LINK CASCADE;
CREATE TABLE AS_FS_CHS_COMPANY_LINK (
    COMPANY_LINK_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    CHARGES VARCHAR(255),
    FILLING_HISTORY VARCHAR(255),
    INSOLVENCY VARCHAR(255),
    OFFICERS VARCHAR(255),
    OVERSEAS VARCHAR(255),
    PERSONS_WITH_SIGNIFICANT_CONTROL VARCHAR(255),
    PERSONS_WITH_SIGNIFICANT_CONTROL_STATEMENTS VARCHAR(255),
    REGISTERS VARCHAR(255),
    SELF VARCHAR(255),
    UK_ESTABLISHMENTS VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
