-- Source Appian CDT: AS_FS_CHS_PreviousCompanyDetails
-- Description: refers to AS_FS_CHS_PREVIOUS_COMPANY_DETAILS entity fields
DROP TABLE IF EXISTS AS_FS_CHS_PREVIOUS_COMPANY_DETAILS CASCADE;
CREATE TABLE AS_FS_CHS_PREVIOUS_COMPANY_DETAILS (
    PREVIOUS_COMPANY_DETAILS_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    COMPANY_DETAILS_ID INT,
    CEASED_ON DATE,
    EFFECTIVE_FROM DATE,
    PREVIOUS_COMPANY_NAME VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
