-- Source Appian CDT: AS_FS_ALT_A_AlertConfiguration
-- Description: Audit table for alert configuration
DROP TABLE IF EXISTS AS_FS_ALT_A_ALERT_CONFIGURATION CASCADE;
CREATE TABLE AS_FS_ALT_A_ALERT_CONFIGURATION (
    ALERT_CONFIGURATION_AUDIT_ID INT PRIMARY KEY,
    ALERT_CONFIGURATION_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255),
    ALERT_CONFIGURATION_FILTER_SET_AUDIT_ID INT,
    ALERT_CONFIGURATION_TRIGGER_SET_AUDIT_ID INT
);
