-- Source Appian CDT: AS_FS_Fee
-- Description: fees for a product/account
DROP TABLE IF EXISTS AS_FS_FEE CASCADE;
CREATE TABLE AS_FS_FEE (
    FEE_ID INT PRIMARY KEY,
    PRODUCT_ID INT,
    FEE DOUBLE PRECISION,
    TYPE VARCHAR(255),
    AD_VALOREM DOUBLE PRECISION,
    TRANSACTION_CHARGE DOUBLE PRECISION,
    TRANSACTION_CURRENCY_CODE VARCHAR(255),
    FEE_CURRENCY_CODE VARCHAR(255),
    COUNTRY_ID INT
);
