-- Source Appian CDT: AS_FS_DOCUSIGN_R_DocSignatureContext
-- Description: Reference for DocSignatureContext
DROP TABLE IF EXISTS AS_FS_DOCUSIGN_R_DOC_SIGNATURE_CONTEXT CASCADE;
CREATE TABLE AS_FS_DOCUSIGN_R_DOC_SIGNATURE_CONTEXT (
    DOC_SIGNATURE_CONTEXT_REF_ID INT PRIMARY KEY,
    DOCUMENT_TYPE_CODE VARCHAR(255),
    UNSIGNED_DOCUMENT_ID INT
);
