-- Source Appian CDT: AS_FS_DOCUSIGN_DocSignatureContext
-- Description: CDT for Document Signature Context(Docusign).
DROP TABLE IF EXISTS AS_FS_DOCUSIGN_DOC_SIGNATURE_CONTEXT CASCADE;
CREATE TABLE AS_FS_DOCUSIGN_DOC_SIGNATURE_CONTEXT (
    DOC_SIGNATURE_CONTEXT_ID INT PRIMARY KEY,
    DOCUMENT_TYPE_CODE VARCHAR(255),
    UNSIGNED_DOCUMENT_ID INT,
    ENVELOPE_ID VARCHAR(255),
    SIGNED_DOCUMENT_ID INT
);
