-- Source Appian CDT: AS_FS_ALT_A_AlertConfigurationFilterCondition
-- Description: CDT for audit alert configuration filter condition
DROP TABLE IF EXISTS AS_FS_ALT_A_ALERT_CONFIGURATION_FILTER_CONDITION CASCADE;
CREATE TABLE AS_FS_ALT_A_ALERT_CONFIGURATION_FILTER_CONDITION (
    ALERT_CONFIGURATION_FILTER_CONDITION_AUDIT_ID INT PRIMARY KEY,
    ALERT_CONFIGURATION_FILTER_CONDITION_ID INT,
    ALERT_CONFIGURATION_FILTER_SET_AUDIT_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
