-- Source Appian CDT: AS_FS_ALT_A_AlertConfiguration_Field
-- Description: Audit table for Alert configuration field
DROP TABLE IF EXISTS AS_FS_ALT_A_ALERT_CONFIGURATION_FIELD CASCADE;
CREATE TABLE AS_FS_ALT_A_ALERT_CONFIGURATION_FIELD (
    ALERT_CONFIGURATION_AUDIT_FIELD_ID INT PRIMARY KEY,
    ALERT_CONFIGURATION_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
