-- Source Appian CDT: AS_FS_CustomerRelation
-- Description: Mapping table between customers for relationships
DROP TABLE IF EXISTS AS_FS_CUSTOMER_RELATION CASCADE;
CREATE TABLE AS_FS_CUSTOMER_RELATION (
    CUSTOMER_RELATION_ID INT PRIMARY KEY,
    FROM_CUSTOMER_ID INT,
    TO_CUSTOMER_ID INT,
    PERCENT_OWNED DOUBLE PRECISION,
    IS_ACTIVE BOOLEAN,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
