-- Source Appian CDT: AS_FS_R_Region
-- Description: Reference data for Region
DROP TABLE IF EXISTS AS_FS_R_REGION CASCADE;
CREATE TABLE AS_FS_R_REGION (
    REGION_ID INT PRIMARY KEY,
    REGION_CODE VARCHAR(255),
    REGION_NAME VARCHAR(255),
    IS_ACTIVE BOOLEAN
);
