-- Source Appian CDT: AS_FS_R_Country
-- Description: Country Reference data
DROP TABLE IF EXISTS AS_FS_R_COUNTRY CASCADE;
CREATE TABLE AS_FS_R_COUNTRY (
    COUNTRY_CODE VARCHAR(255) PRIMARY KEY,
    COUNTRY_NAME VARCHAR(255),
    REGION_CODE VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    SORT_ORDER INT,
    FLAG_UNICODE_JSON VARCHAR(255)
);
