-- Source Appian CDT: AS_FS_CHS_R_Data
-- Description: refers to AS_FS_CHS_R_DATA entity fields
DROP TABLE IF EXISTS AS_FS_CHS_R_DATA CASCADE;
CREATE TABLE AS_FS_CHS_R_DATA (
    R_DATA_ID INT PRIMARY KEY,
    LABEL VARCHAR(255),
    TYPE VARCHAR(255),
    CODE VARCHAR(255),
    SORT_ORDER INT,
    ICON VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
