-- Source Appian CDT: AS_FS_ALT_CONF_AlertConfigurationTriggerSet
-- Description: AlertConfigurationTriggerSet Datatype for AS_FS Alert Configuration
DROP TABLE IF EXISTS AS_FS_ALT_CONF_ALERT_CONFIGURATION_TRIGGER_SET CASCADE;
CREATE TABLE AS_FS_ALT_CONF_ALERT_CONFIGURATION_TRIGGER_SET (
    ALERT_CONFIGURATION_TRIGGER_SET_ID INT PRIMARY KEY,
    OPERATOR VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
