-- Source Appian CDT: AS_FS_REF_A_R_Data_Field
-- Description: Holds auditing data for `AS_FS_REF_R_DATA` - simple field change
DROP TABLE IF EXISTS AS_FS_REF_A_R_DATA_FIELD CASCADE;
CREATE TABLE AS_FS_REF_A_R_DATA_FIELD (
    R_DATA_AUDIT_FIELD_ID INT PRIMARY KEY,
    R_DATA_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
