-- Source Appian CDT: AS_FS_ALT_A_AlertConfigurationFilterCondition_Field
-- Description: CDT for alert configuration filter condition fields
DROP TABLE IF EXISTS AS_FS_ALT_A_ALERT_CONFIGURATION_FILTER_CONDITION_FIELD CASCADE;
CREATE TABLE AS_FS_ALT_A_ALERT_CONFIGURATION_FILTER_CONDITION_FIELD (
    ALERT_CONFIGURATION_FILTER_CONDITION_FIELD_ID INT PRIMARY KEY,
    ALERT_CONFIGURATION_FILTER_CONDITION_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
