-- Source Appian CDT: AS_FS_IDP_A_Preferences
-- Description: CDT for Auditing preferences
DROP TABLE IF EXISTS AS_FS_IDP_A_PREFERENCES CASCADE;
CREATE TABLE AS_FS_IDP_A_PREFERENCES (
    PREFERENCES_AUDIT_ID INT PRIMARY KEY,
    CHANNEL_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
