-- Source Appian CDT: AS_FS_CHS_A_CompanyDetails
-- Description: CDT to audit changes for Company Details(Companies House).
DROP TABLE IF EXISTS AS_FS_CHS_A_COMPANY_DETAILS CASCADE;
CREATE TABLE AS_FS_CHS_A_COMPANY_DETAILS (
    COMPANY_DETAILS_AUDIT_ID INT PRIMARY KEY,
    COMPANY_DETAILS_ID INT,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
