-- Source Appian CDT: AS_FS_ALT_CONF_AlertConfigurationFilterCondition
-- Description: CDT for Alert configuration filter condition
DROP TABLE IF EXISTS AS_FS_ALT_CONF_ALERT_CONFIGURATION_FILTER_CONDITION CASCADE;
CREATE TABLE AS_FS_ALT_CONF_ALERT_CONFIGURATION_FILTER_CONDITION (
    ALERT_CONFIGURATION_FILTER_CONDITION_ID INT PRIMARY KEY,
    ALERT_CONFIGURATION_FILTER_SET_ID INT,
    ALERT_CONFIGURATION_FILTER_TYPE_CODE VARCHAR(255),
    OPERATOR VARCHAR(255),
    CONFIGURATION_FILTER_SETTINGS VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
