-- Source Appian CDT: AS_FS_IDP_DocUnderstanding
-- Description: Cdt for Doc Understanding
DROP TABLE IF EXISTS AS_FS_IDP_DOC_UNDERSTANDING CASCADE;
CREATE TABLE AS_FS_IDP_DOC_UNDERSTANDING (
    UNDERSTANDING_ID INT PRIMARY KEY,
    DOCUMENT_ID INT,
    documentName VARCHAR(255),
    CHANNEL_ID INT,
    RECEIVED_ON TIMESTAMP,
    understandingStatus VARCHAR(255),
    jobGuid VARCHAR(255),
    cloudStorageUri VARCHAR(255),
    IS_PRE_CLASSIFIED BOOLEAN,
    PREDICTED_DOC_TYPE_ID INT,
    DOC_TYPE_CONF DOUBLE PRECISION,
    DOC_TYPE_ID INT,
    IS_CLASSIFICATION_VERIFIED BOOLEAN,
    CLASSIFICATION_ACCEPTED_ON TIMESTAMP,
    CLASSIFICATION_COMPLETED_ON TIMESTAMP,
    classifiedBy VARCHAR(255),
    USE_CLASSIFICATION BOOLEAN,
    IS_STRUCTURED BOOLEAN
);
