-- Source Appian CDT: AS_FS_R_State
-- Description: US State Reference Data
DROP TABLE IF EXISTS AS_FS_R_STATE CASCADE;
CREATE TABLE AS_FS_R_STATE (
    STATE_ID INT PRIMARY KEY,
    STATE_NAME VARCHAR(255),
    STATE_CODE VARCHAR(255),
    IS_TERRITORY BOOLEAN,
    IS_ACTIVE BOOLEAN,
    SORT_ORDER INT
);
