-- Source Appian CDT: AS_FS_IDP_DocType
-- Description: Cdt for Doc Type
DROP TABLE IF EXISTS AS_FS_IDP_R_DOC_TYPE CASCADE;
CREATE TABLE AS_FS_IDP_R_DOC_TYPE (
    DOC_TYPE_ID INT PRIMARY KEY,
    docTypeName VARCHAR(255),
    docTypeCode VARCHAR(255),
    docTypeStatus VARCHAR(255),
    IS_INVALID_TYPE BOOLEAN,
    CHANNEL_ID INT,
    IS_TRAINING_SUCCESSFUL BOOLEAN
);
