-- Source Appian CDT: AS_FS_A_Product
-- Description: Data type refers to the attributes related to the product audit
DROP TABLE IF EXISTS AS_FS_A_PRODUCT CASCADE;
CREATE TABLE AS_FS_A_PRODUCT (
    PRODUCT_AUDIT_ID INT PRIMARY KEY,
    PRODUCT_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255),
    TERM_AUDIT_ID INT
);
