-- Source Appian CDT: AS_FS_A_AllUserSettings
-- Description: Audit CDT for AllUserSettings table
DROP TABLE IF EXISTS AS_FS_A_R_ALL_USER_SETTINGS CASCADE;
CREATE TABLE AS_FS_A_R_ALL_USER_SETTINGS (
    USER_SETTINGS_AUDIT_ID INT PRIMARY KEY,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
