-- Source Appian CDT: AS_FS_ALT_A_AlertConfigurationTriggerSet_Field
-- Description: Audit table for alert configuration trigger
DROP TABLE IF EXISTS AS_FS_ALT_A_ALERT_CONFIGURATION_TRIGGER_SET_FIELD CASCADE;
CREATE TABLE AS_FS_ALT_A_ALERT_CONFIGURATION_TRIGGER_SET_FIELD (
    ALERT_CONFIGURATION_TRIGGER_SET_AUDIT_FIELD_ID INT PRIMARY KEY,
    ALERT_CONFIGURATION_TRIGGER_SET_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
