-- Source Appian CDT: AS_FS_CHS_ForeignCompanyDetails
-- Description: refers to AS_FS_CHS_FOREIGN_COMPANY_DETAILS entity fileds
DROP TABLE IF EXISTS AS_FS_CHS_FOREIGN_COMPANY_DETAILS CASCADE;
CREATE TABLE AS_FS_CHS_FOREIGN_COMPANY_DETAILS (
    FOREIGN_COMPANY_DETAILS_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    FOREIGN_ACCOUNT_TYPE VARCHAR(255),
    TERMS_OF_ACCOUNT_PUBLICATION VARCHAR(255),
    ACCOUNT_PERIOD_FROM_DAY INT,
    ACCOUNT_PERIOD_FROM_MONTH INT,
    ACCOUNT_PERIOD_TO_DAY INT,
    ACCOUNT_PERIOD_TO_MONTH INT,
    MUST_FILE_WITHIN_MONTHS INT,
    BUSINESS_ACTIVITY VARCHAR(255),
    COMPANY_TYPE VARCHAR(255),
    GOVERNED_BY VARCHAR(255),
    IS_CREDIT_FINANCE_INSTITUTION BOOLEAN,
    ORIGINATING_REGISTRY_COUNTRY VARCHAR(255),
    ORIGINATING_REGISTRY_NAME VARCHAR(255),
    REGISTRATION_NUMBER VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
