-- Source Appian CDT: AS_FS_A_Address
-- Description: Holds auditing data for `AS_FS_Address`
DROP TABLE IF EXISTS AS_FS_A_ADDRESS CASCADE;
CREATE TABLE AS_FS_A_ADDRESS (
    ADDRESS_AUDIT_ID INT PRIMARY KEY,
    CONTACT_AUDIT_ID INT,
    ADDRESS_ID INT,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
