-- Source Appian CDT: AS_FS_IDP_DocChannel
-- Description: Cdt for Doc Channel
DROP TABLE IF EXISTS AS_FS_IDP_R_DOC_CHANNEL CASCADE;
CREATE TABLE AS_FS_IDP_R_DOC_CHANNEL (
    CHANNEL_ID INT PRIMARY KEY,
    CHANNEL_NAME VARCHAR(255),
    MODEL_ID VARCHAR(255),
    MODEL_TRAINED_ON TIMESTAMP,
    NUM_DOCS_USED_FOR_TRAINING INT,
    INVALID_TYPE_INCLUDED_IN_MODEL BOOLEAN,
    USE_CLASSIFICATION BOOLEAN
);
