-- Source Appian CDT: AS_FS_Customer
-- Description: Data type for customer attributes
DROP TABLE IF EXISTS AS_FS_CUSTOMER CASCADE;
CREATE TABLE AS_FS_CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    CUSTOMER_ACRONYM VARCHAR(255),
    IS_INTERNATIONAL BOOLEAN,
    DOMICILE INT,
    CUSTOMER_TYPE_CODE VARCHAR(255),
    RISK_SCORE INT,
    DUNS VARCHAR(255),
    CUSTOMER_NUMBER VARCHAR(255),
    GMEI VARCHAR(255),
    TAX_ID VARCHAR(255),
    IS_QIB BOOLEAN,
    IS_ERISA BOOLEAN,
    INDUSTRY_CLASSIFICATION_CODE VARCHAR(255),
    FOLDER_ID INT,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    IS_DELETED BOOLEAN,
    ALERT_SET_ID INT,
    GROUP_ID INT,
    VALID_THROUGH_DATE DATE
);
