-- Source Appian CDT: AS_FS_A_BeneficialOwner_Field
-- Description: Holds auditing data for `AS_FS_BeneficialOwner` - simple field change
DROP TABLE IF EXISTS AS_FS_A_BENEFICIAL_OWNER_FIELD CASCADE;
CREATE TABLE AS_FS_A_BENEFICIAL_OWNER_FIELD (
    BENEFICIAL_OWNER_AUDIT_FIELD_ID INT PRIMARY KEY,
    BENEFICIAL_OWNER_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
