-- Source Appian CDT: AS_FS_A_CustomerRelation
-- Description: Holds auditing data for `AS_FS_CustomerRelation`
DROP TABLE IF EXISTS AS_FS_A_CUSTOMER_RELATION CASCADE;
CREATE TABLE AS_FS_A_CUSTOMER_RELATION (
    CUSTOMER_RELATION_AUDIT_ID INT PRIMARY KEY,
    CUSTOMER_RELATION_ID INT,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
