-- Source Appian CDT: AS_FS_ALT_CONF_AlertConfiguration
-- Description: Alert Configuration datatype for AS_FS.
DROP TABLE IF EXISTS AS_FS_ALT_CONF_ALERT_CONFIGURATION CASCADE;
CREATE TABLE AS_FS_ALT_CONF_ALERT_CONFIGURATION (
    ALERT_CONFIGURATION_ID INT PRIMARY KEY,
    ALERT_CONFIGURATION_NAME VARCHAR(255),
    ALERT_TEXT VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    ALERT_CONFIGURATION_FILTER_SET_ID INT,
    ALERT_CONFIGURATION_TRIGGER_SET_ID INT
);
