-- Source Appian CDT: AS_FS_CHS_A_PreviousCompanyDetails
-- Description: Holds auditing data for `AS_FS_CHS_PreviousCompanyDetails`
DROP TABLE IF EXISTS AS_FS_CHS_A_PREVIOUS_COMPANY_DETAILS CASCADE;
CREATE TABLE AS_FS_CHS_A_PREVIOUS_COMPANY_DETAILS (
    PREVIOUS_COMPANY_DETAILS_AUDIT_ID INT PRIMARY KEY,
    COMPANY_DETAILS_AUDIT_ID INT,
    PREVIOUS_COMPANY_DETAILS_ID INT,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
