-- Source Appian CDT: AS_FS_CHS_A_PreviousCompanyDetails_Field
-- Description: Holds auditing data for `AS_FS_CHS_PreviousCompanyDetails` - simple field change
DROP TABLE IF EXISTS AS_FS_CHS_A_PREVIOUS_COMPANY_DETAILS_FIELD CASCADE;
CREATE TABLE AS_FS_CHS_A_PREVIOUS_COMPANY_DETAILS_FIELD (
    PREVIOUS_COMPANY_DETAILS_AUDIT_FIELD_ID INT PRIMARY KEY,
    PREVIOUS_COMPANY_DETAILS_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
