-- Source Appian CDT: AS_FS_CHS_A_CompanyDetailsField
-- Description: CDT to map field changes for Audit purpose.
DROP TABLE IF EXISTS AS_FS_CHS_A_COMPANY_DETAILS_FIELD CASCADE;
CREATE TABLE AS_FS_CHS_A_COMPANY_DETAILS_FIELD (
    COMPANY_DETAILS_AUDIT_FIELD_ID INT PRIMARY KEY,
    COMPANY_DETAILS_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
