-- Source Appian CDT: AS_FS_A_Account
-- Description: Data type refers to the attributes related to the account audit
DROP TABLE IF EXISTS AS_FS_A_ACCOUNT CASCADE;
CREATE TABLE AS_FS_A_ACCOUNT (
    ACCOUNT_AUDIT_ID INT PRIMARY KEY,
    ACCOUNT_ID INT,
    PRODUCT_AUDIT_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
