-- Source Appian CDT: AS_FS_ALT_A_AlertConfigurationEvent
-- Description: Audit table for alert configuration event
DROP TABLE IF EXISTS AS_FS_ALT_A_ALERT_CONFIGURATION_EVENT CASCADE;
CREATE TABLE AS_FS_ALT_A_ALERT_CONFIGURATION_EVENT (
    ALERT_CONFIGURATION_EVENT_AUDIT_ID INT PRIMARY KEY,
    ALERT_CONFIGURATION_EVENT_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255),
    EVENT_TYPE_CODE VARCHAR(255)
);
