-- Source Appian CDT: AS_FS_IDP_A_Preferences_Field
-- Description: Audit field  cdt for Preferences
DROP TABLE IF EXISTS AS_FS_IDP_A_PREFERENCES_FIELD CASCADE;
CREATE TABLE AS_FS_IDP_A_PREFERENCES_FIELD (
    PREFERENCES_AUDIT_FIELD_ID INT PRIMARY KEY,
    PREFERENCES_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
