-- Source Appian CDT: AS_FS_ALT_CONF_AlertConfigurationTriggerCondition
-- Description: CDT for Alert configuration trigger condition
DROP TABLE IF EXISTS AS_FS_ALT_CONF_ALERT_CONFIGURATION_TRIGGER_CONDITION CASCADE;
CREATE TABLE AS_FS_ALT_CONF_ALERT_CONFIGURATION_TRIGGER_CONDITION (
    ALERT_CONFIGURATION_TRIGGER_CONDITION_ID INT PRIMARY KEY,
    ALERT_CONFIGURATION_TRIGGER_SET_ID INT,
    ALERT_CONFIGURATION_TRIGGER_TYPE_CODE VARCHAR(255),
    CONFIGURATION_TRIGGER_SETTINGS VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
