-- Source Appian CDT: AS_FS_ALT_A_AlertConfigurationEvent_Field
-- Description: Audit table for Alert configuration event
DROP TABLE IF EXISTS AS_FS_ALT_A_ALERT_CONFIGURATION_EVENT_FIELD CASCADE;
CREATE TABLE AS_FS_ALT_A_ALERT_CONFIGURATION_EVENT_FIELD (
    ALERT_CONFIGURATION_AUDIT_FIELD_ID INT PRIMARY KEY,
    ALERT_CONFIGURATION_EVENT_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
