-- Source Appian CDT: AS_FS_ALT_CONF_AlertConfigurationFilterSet
-- Description: AlertConfigurationFilerSet Datatype for AS_FS
DROP TABLE IF EXISTS AS_FS_ALT_CONF_ALERT_CONFIGURATION_FILTER_SET CASCADE;
CREATE TABLE AS_FS_ALT_CONF_ALERT_CONFIGURATION_FILTER_SET (
    ALERT_CONFIGURATION_FILTER_SET_ID INT PRIMARY KEY,
    OPERATOR VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
