-- Source Appian CDT: AS_FS_Contact
-- Description: Contact information for a record in FS namespace
DROP TABLE IF EXISTS AS_FS_CONTACT CASCADE;
CREATE TABLE AS_FS_CONTACT (
    CONTACT_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    TITLE VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    POSITION VARCHAR(255),
    EMAIL VARCHAR(255),
    CONTACT_TYPE VARCHAR(255),
    RELATIONSHIP_TYPE VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
