-- Source Appian CDT: AS_GM_userDetails
-- Description: Holds the user details in the group management
DROP TABLE IF EXISTS AS_GM_USER_DETAILS CASCADE;
CREATE TABLE AS_GM_USER_DETAILS (
    USER_DETAILS_ID INT PRIMARY KEY,
    USER_NAME VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
