-- Source Appian CDT: AS_IO_OnboardingFundingDetails
-- Description: Data type for the attributes related to funding details of an onboarding
DROP TABLE IF EXISTS AS_IO_ONBOARDING_FUNDING_DETAILS CASCADE;
CREATE TABLE AS_IO_ONBOARDING_FUNDING_DETAILS (
    FUNDING_DETAILS_ID INT PRIMARY KEY,
    EST_FUNDING_DATE DATE,
    EST_FUNDING_VALUE DOUBLE PRECISION,
    EST_VALUE_CURRENCY_CODE VARCHAR(255),
    ACTUAL_FUNDING_DATE DATE,
    ACTUAL_FUNDING_VALUE DOUBLE PRECISION,
    ACTUAL_VALUE_CURRENCY_CODE VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
