-- Source Appian CDT: AS_IO_A_T_RequiredDocument
-- Description: Holds auditing data for `AS_IO_T_RequiredDocument`
DROP TABLE IF EXISTS AS_IO_A_T_REQUIRED_DOCUMENT CASCADE;
CREATE TABLE AS_IO_A_T_REQUIRED_DOCUMENT (
    REQUIRED_DOCUMENT_TEMPLATE_AUDIT_ID INT PRIMARY KEY,
    REQUIRED_DOCUMENT_TEMPLATE_ID INT,
    TEMPLATE_AUDIT_ID INT,
    AUDIT_ACTION_CODE VARCHAR(255),
    USERNAME VARCHAR(255),
    TIMESTAMP TIMESTAMP
);
