-- Source Appian CDT: AS_IO_A_T_OnboardingProduct_Field
-- Description: Holds auditing data for `AS_IO_T_OnboardingProduct` - simple field change
DROP TABLE IF EXISTS AS_IO_A_T_ONBOARDING_PRODUCT_FIELD CASCADE;
CREATE TABLE AS_IO_A_T_ONBOARDING_PRODUCT_FIELD (
    ONBOARDING_PRODUCT_TEMPLATE_AUDIT_FIELD_ID INT PRIMARY KEY,
    ONBOARDING_PRODUCT_TEMPLATE_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
