-- Source Appian CDT: AS_IO_ProductRequiredDocumentMap
-- Description: Maps Product with required document codes
DROP TABLE IF EXISTS AS_IO_PRODUCT_REQUIRED_DOCUMENT_MAP CASCADE;
CREATE TABLE AS_IO_PRODUCT_REQUIRED_DOCUMENT_MAP (
    PRODUCT_REQUIRED_DOCUMENT_MAP_ID INT PRIMARY KEY,
    REQUIRED_DOC_TYPE_CODE VARCHAR(255),
    PRODUCT_ID INT
);
