-- Source Appian CDT: AS_IO_A_R_Template_Field
-- Description: Holds auditing data for `AS_IO_R_Template` - simple field change
DROP TABLE IF EXISTS AS_IO_A_R_TEMPLATE_FIELD CASCADE;
CREATE TABLE AS_IO_A_R_TEMPLATE_FIELD (
    TEMPLATE_AUDIT_FIELD_ID INT PRIMARY KEY,
    TEMPLATE_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
