-- Source Appian CDT: AS_IO_R_TemplateTask
-- Description: Maps tasks to a template; includes reference data and precedents
DROP TABLE IF EXISTS AS_IO_R_TEMPLATE_TASK CASCADE;
CREATE TABLE AS_IO_R_TEMPLATE_TASK (
    TEMPLATE_TASK_ID INT PRIMARY KEY,
    TEMPLATE_ID INT,
    TASK_REF_ID INT,
    ORDER_NUMBER INT,
    GROUP_ASSIGNEE INT,
    REQUIRED_DOCUMENT_TEMPLATE_UUID VARCHAR(255),
    TEMPLATE_TASK_UUID VARCHAR(255),
    TASK_NAME VARCHAR(255),
    TASK_DESC VARCHAR(255),
    SLA_DAYS INT,
    SLA_RULE VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
