-- Source Appian CDT: AS_IO_A_RequiredDocument
-- Description: Audit For required Document
DROP TABLE IF EXISTS AS_IO_A_REQUIRED_DOCUMENT CASCADE;
CREATE TABLE AS_IO_A_REQUIRED_DOCUMENT (
    REQUIRED_DOCUMENT_AUDIT_ID INT PRIMARY KEY,
    REQUIRED_ONBOARDING_DOCUMENT_ID INT,
    AUDIT_ACTION_CODE VARCHAR(255),
    USERNAME VARCHAR(255),
    TIMESTAMP TIMESTAMP
);
