-- Source Appian CDT: AS_IO_Product_P
-- Description: Data type for the attributes related to the products of a request

For more information see: https://docs.google.com/document/d/1dQpJ2O4U1weA6AdR9FrjETKV46sNBZFd62Bb2h-2il8/edit
DROP TABLE IF EXISTS AS_IO_PRODUCT CASCADE;
CREATE TABLE AS_IO_PRODUCT (
    PRODUCT_ID INT PRIMARY KEY,
    REQUEST_ID INT,
    FUND_ID INT,
    NAME VARCHAR(255),
    PRODUCT_TYPE_CODE VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    ENTITY VARCHAR(255),
    ENTITY_TYPE VARCHAR(255),
    STRATEGY VARCHAR(255),
    VALUE DOUBLE PRECISION,
    VALUE_CURRENCY_CODE VARCHAR(255),
    DURATION INT,
    UPFRONT_FEE DOUBLE PRECISION,
    COMMITMENT_FEE DOUBLE PRECISION,
    INTEREST DOUBLE PRECISION,
    COVER_REQUIRED DOUBLE PRECISION,
    COLLATERAL VARCHAR(255),
    COLLATERAL_VALUE DOUBLE PRECISION,
    COLLATERAL_CURRENCY_CODE VARCHAR(255),
    COVER_PROVIDED DOUBLE PRECISION,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    IS_PARENT BOOLEAN,
    IS_DELETED BOOLEAN,
    TERM_ID INT
);
