-- Source Appian CDT: AS_IO_A_TemplateProcessSetup
-- Description: Holds auditing data for process setup
DROP TABLE IF EXISTS AS_IO_A_TEMPLATE_PROCESS_SETUP CASCADE;
CREATE TABLE AS_IO_A_TEMPLATE_PROCESS_SETUP (
    TEMPLATE_PROC_SETUP_AUDIT_ID INT PRIMARY KEY,
    TASK_ID_PROCESS_SETUP INT,
    ORIGINAL_TEMPLATE_ID INT,
    NEW_TEMPLATE_ID INT,
    RECORD_ID INT,
    TIME_STAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    TEMPLATE_AUDIT_ACTION_CODE VARCHAR(255)
);
