-- Source Appian CDT: AS_IO_A_OnboardingDocument_Field
-- Description: Field level Audit for Onboarding Document
DROP TABLE IF EXISTS AS_IO_A_ONBOARDING_DOCUMENT_FIELD CASCADE;
CREATE TABLE AS_IO_A_ONBOARDING_DOCUMENT_FIELD (
    ONBOARDING_DOCUMENT_AUDIT_FIELD_ID INT PRIMARY KEY,
    ONBOARDING_DOCUMENT_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255),
    COMMENT VARCHAR(255)
);
