-- Source Appian CDT: AS_IO_T_OnboardingAccountTypeProductTypeMapping
-- Description: Mapping CDT for account types and product types in onboarding templates
DROP TABLE IF EXISTS AS_IO_T_ONBOARDING_ACCOUNT_TYPE_PRODUCT_TYPE_MAPPING CASCADE;
CREATE TABLE AS_IO_T_ONBOARDING_ACCOUNT_TYPE_PRODUCT_TYPE_MAPPING (
    ONBOARDING_ACCOUNT_TYPE_PRODUCT_TYPE_MAPPING_ID INT PRIMARY KEY,
    ACCOUNT_TYPE_CODE VARCHAR(255),
    ONBOARDING_PRODUCT_TEMPLATE_ID INT,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
