-- Source Appian CDT: AS_IO_Owner
-- Description: Data type for request owners
DROP TABLE IF EXISTS AS_IO_OWNER CASCADE;
CREATE TABLE AS_IO_OWNER (
    OWNER_ID INT PRIMARY KEY,
    REQUEST_ID INT,
    OWNER VARCHAR(255),
    OWNER_GROUP INT,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    IS_DELETED BOOLEAN
);
