-- Source Appian CDT: AS_IO_R_TaskStatus
-- Description: Reference data table for a task behavior type
DROP TABLE IF EXISTS AS_IO_R_TASK_STATUS CASCADE;
CREATE TABLE AS_IO_R_TASK_STATUS (
    TASK_STATUS_ID INT PRIMARY KEY,
    STATUS_DISPLAY_NAME VARCHAR(255),
    ICON VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
