-- Source Appian CDT: AS_IO_A_R_Template
-- Description: Holds auditing data for `AS_IO_R_Template`
DROP TABLE IF EXISTS AS_IO_A_R_TEMPLATE CASCADE;
CREATE TABLE AS_IO_A_R_TEMPLATE (
    TEMPLATE_AUDIT_ID INT PRIMARY KEY,
    TEMPLATE_ID INT,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
