-- Source Appian CDT: AS_IO_Term
-- Description: Data type for account terms
DROP TABLE IF EXISTS AS_IO_TERM CASCADE;
CREATE TABLE AS_IO_TERM (
    TERM_ID INT PRIMARY KEY,
    PERFORMANCE_START_DATE DATE,
    PERFORMANCE_RETURN_TERM INT,
    COMMITTED_MARGIN INT,
    RATE_LOCK INT,
    SHORT_LOCK INT,
    OTHER_TERM VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    IS_DELETED BOOLEAN
);
