-- Source Appian CDT: AS_IO_A_T_RequiredDocument_Field
-- Description: Holds auditing data for `AS_IO_T_RequiredDocument` - simple field change
DROP TABLE IF EXISTS AS_IO_A_T_REQUIRED_DOCUMENT_FIELD CASCADE;
CREATE TABLE AS_IO_A_T_REQUIRED_DOCUMENT_FIELD (
    REQUIRED_DOCUMENT_TEMPLATE_AUDIT_FIELD_ID INT PRIMARY KEY,
    REQUIRED_DOCUMENT_TEMPLATE_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
