-- Source Appian CDT: AS_IO_T_OnboardingProduct
-- Description: Onboarding Products that are added to onboarding templates
DROP TABLE IF EXISTS AS_IO_T_ONBOARDING_PRODUCT CASCADE;
CREATE TABLE AS_IO_T_ONBOARDING_PRODUCT (
    ONBOARDING_PRODUCT_TEMPLATE_ID INT PRIMARY KEY,
    PRODUCT_TYPE_CODE VARCHAR(255),
    TEMPLATE_ID INT,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
