-- Source Appian CDT: AS_IO_Country
-- Description: Data type for a country
DROP TABLE IF EXISTS AS_IO_COUNTRY CASCADE;
CREATE TABLE AS_IO_COUNTRY (
    COUNTRY_ID INT PRIMARY KEY,
    PRODUCT_ID INT,
    COUNTRY_CODE VARCHAR(255),
    IS_TRADING_ALLOWED BOOLEAN,
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    IS_DELETED BOOLEAN
);
