-- Source Appian CDT: AS_IO_R_TaskAction
-- Description: Reference data table for a task behavior type
DROP TABLE IF EXISTS AS_IO_R_TASK_ACTION CASCADE;
CREATE TABLE AS_IO_R_TASK_ACTION (
    TASK_ACTION_ID INT PRIMARY KEY,
    ACTION_DISPLAY_NAME VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
