-- Source Appian CDT: AS_IO_Fund
-- Description: Data type for request funds
DROP TABLE IF EXISTS AS_IO_FUND CASCADE;
CREATE TABLE AS_IO_FUND (
    FUND_ID INT PRIMARY KEY,
    REQUEST_ID INT,
    CUSTOMER_ID INT,
    NAME VARCHAR(255),
    REGION_CODE VARCHAR(255),
    DOMICILE VARCHAR(255),
    ADDRESS VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    IS_DELETED BOOLEAN
);
