-- Source Appian CDT: AS_IO_R_AccountType_ProductType_Mapping
DROP TABLE IF EXISTS AS_IO_R_ACCOUNT_TYPE_PRODUCT_TYPE_MAPPING CASCADE;
CREATE TABLE AS_IO_R_ACCOUNT_TYPE_PRODUCT_TYPE_MAPPING (
    ACCOUNT_TYPE_PRODUCT_TYPE_MAPPING_ID INT PRIMARY KEY,
    ACCOUNT_TYPE_CODE VARCHAR(255),
    PRODUCT_TYPE_CODE VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    IS_ACTIVE BOOLEAN
);
