-- Source Appian CDT: AS_IO_R_TaskBehaviorType
-- Description: Reference data table for a task behavior type
DROP TABLE IF EXISTS AS_IO_R_TASK_BEHAVIOR_TYPE CASCADE;
CREATE TABLE AS_IO_R_TASK_BEHAVIOR_TYPE (
    TASK_BEHAVIOR_TYPE_ID INT PRIMARY KEY,
    BEHAVIOR_TYPE_CODE VARCHAR(255),
    BEHAVIOR_SUBTYPE_CODE VARCHAR(255),
    BEHAVIOR_DISPLAY_NAME VARCHAR(255),
    CONFIGURATION_LEVEL_CODE VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    ICON VARCHAR(255)
);
