-- Source Appian CDT: AS_IO_REF_A_R_Data
-- Description: Audit structure for AS_IO_REF_R_Data
DROP TABLE IF EXISTS AS_IO_REF_A_R_DATA CASCADE;
CREATE TABLE AS_IO_REF_A_R_DATA (
    R_DATA_AUDIT_ID INT PRIMARY KEY,
    R_DATA_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
