-- Source Appian CDT: AS_IO_A_R_TaskCategory_Field
-- Description: Holds auditing data for `AS_IO_R_TaskCategory` - simple field change
DROP TABLE IF EXISTS AS_IO_A_R_TASK_CATEGORY_FIELD CASCADE;
CREATE TABLE AS_IO_A_R_TASK_CATEGORY_FIELD (
    TASK_CATEGORY_AUDIT_FIELD_ID INT PRIMARY KEY,
    TASK_CATEGORY_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
