-- Source Appian CDT: AS_IO_A_T_OnboardingProduct
-- Description: Holds auditing data for `AS_IO_T_OnboardingProduct`
DROP TABLE IF EXISTS AS_IO_A_T_ONBOARDING_PRODUCT CASCADE;
CREATE TABLE AS_IO_A_T_ONBOARDING_PRODUCT (
    ONBOARDING_PRODUCT_TEMPLATE_AUDIT_ID INT PRIMARY KEY,
    ONBOARDING_PRODUCT_TEMPLATE_ID INT,
    TEMPLATE_AUDIT_ID INT,
    AUDIT_ACTION_CODE VARCHAR(255),
    USERNAME VARCHAR(255),
    TIMESTAMP TIMESTAMP
);
