-- Source Appian CDT: AS_IO_A_OnboardingFundingDetails
-- Description: Holds auditing data for `AS_IO_OnboardingFundingDetails`
DROP TABLE IF EXISTS AS_IO_A_ONBOARDING_FUNDING_DETAILS CASCADE;
CREATE TABLE AS_IO_A_ONBOARDING_FUNDING_DETAILS (
    FUNDING_DETAILS_AUDIT_ID INT PRIMARY KEY,
    FUNDING_DETAILS_ID INT,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
