-- Source Appian CDT: AS_IO_R_Template
-- Description: Reference templates that are used to define the default task flow for different types of onboarding requests
DROP TABLE IF EXISTS AS_IO_R_TEMPLATE CASCADE;
CREATE TABLE AS_IO_R_TEMPLATE (
    TEMPLATE_ID INT PRIMARY KEY,
    TEMPLATE_NAME VARCHAR(255),
    TEMPLATE_DESC VARCHAR(255),
    ONBOARDING_TYPE_CODE VARCHAR(255),
    REGION_CODE VARCHAR(255),
    SLA_DAY_TYPE VARCHAR(255),
    IS_DEFAULT BOOLEAN,
    IS_ACTIVE BOOLEAN,
    IS_DELETED BOOLEAN,
    TEMPLATE_CUSTOM_FIELDS_ID INT,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
