-- Source Appian CDT: AS_IO_A_TaskProcessSetup
-- Description: Holds auditing data for process setup modification - task change
DROP TABLE IF EXISTS AS_IO_A_TASK_PROCESS_SETUP CASCADE;
CREATE TABLE AS_IO_A_TASK_PROCESS_SETUP (
    TASK_PROC_SETUP_AUDIT_ID INT PRIMARY KEY,
    TEMPLATE_PROC_SETUP_AUDIT_ID INT,
    TEMPLATE_ID INT,
    TASK_REF_ID INT,
    TASK_ID INT,
    RECORD_ID INT,
    TIME_STAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
