-- Source Appian CDT: AS_IO_T_RequiredDocument
-- Description: Onboarding Requirements that are added to onboarding templates
DROP TABLE IF EXISTS AS_IO_T_REQUIRED_DOCUMENT CASCADE;
CREATE TABLE AS_IO_T_REQUIRED_DOCUMENT (
    REQUIRED_DOCUMENT_TEMPLATE_ID INT PRIMARY KEY,
    DOC_TYPE_CODE VARCHAR(255),
    TEMPLATE_ID INT,
    REQUIRED_DOCUMENT_TEMPLATE_UUID VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
