-- Source Appian CDT: AS_IO_R_ProductTypeDocMap
-- Description: maps required documents to the product type
DROP TABLE IF EXISTS AS_IO_R_PRODUCT_TYPE_DOC_MAP CASCADE;
CREATE TABLE AS_IO_R_PRODUCT_TYPE_DOC_MAP (
    PRODUCT_TYPE_DOC_MAP_ID INT PRIMARY KEY,
    PRODUCT_TYPE_CODE VARCHAR(255),
    TYPE_CODE VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    IS_ACTIVE BOOLEAN
);
