-- Source Appian CDT: AS_IO_TaskActionAudit
-- Description: Audit changes to work (runtime tasks)
DROP TABLE IF EXISTS AS_IO_TASK_ACTION_AUDIT CASCADE;
CREATE TABLE AS_IO_TASK_ACTION_AUDIT (
    TASK_ACTION_AUDIT_ID INT PRIMARY KEY,
    TASK_ID INT,
    USERNAME VARCHAR(255),
    TIMESTAMP TIMESTAMP,
    TASK_ACTION_ID INT,
    ASSIGNED_TO VARCHAR(255),
    TASK_REVIEW_ID INT,
    comment VARCHAR(255),
    OLD_DUE_DATE DATE
);
