-- Source Appian CDT: AS_IO_A_OnboardingDocument
-- Description: Audit fields for onboarding Document
DROP TABLE IF EXISTS AS_IO_A_ONBOARDING_DOCUMENT CASCADE;
CREATE TABLE AS_IO_A_ONBOARDING_DOCUMENT (
    ONBOARDING_DOCUMENT_AUDIT_ID INT PRIMARY KEY,
    ONBOARDING_DOCUMENT_ID INT,
    AUDIT_ACTION_CODE VARCHAR(255),
    USERNAME VARCHAR(255),
    TIMESTAMP TIMESTAMP
);
