-- Source Appian CDT: AS_IO_R_OnboardingType_ProductType_Mapping
-- Description: Maps onboarding type to a default list of product types that should be included
DROP TABLE IF EXISTS AS_IO_R_ONBOARDING_TYPE_PRODUCT_TYPE_MAPPING CASCADE;
CREATE TABLE AS_IO_R_ONBOARDING_TYPE_PRODUCT_TYPE_MAPPING (
    ONBOARDING_TYPE_PRODUCT_TYPE_MAPPING_ID INT PRIMARY KEY,
    ONBOARDING_TYPE_CODE VARCHAR(255),
    PRODUCT_TYPE_CODE VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    IS_ACTIVE BOOLEAN
);
