-- Source Appian CDT: AS_IO_A_OnboardingRequest
-- Description: Holds auditing data for `AS_IO_OnboardingRequest`
DROP TABLE IF EXISTS AS_IO_A_ONBOARDING_REQUEST CASCADE;
CREATE TABLE AS_IO_A_ONBOARDING_REQUEST (
    ONBOARDING_AUDIT_ID INT PRIMARY KEY,
    REQUEST_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255),
    COMMENT VARCHAR(255),
    RECORD_ID INT
);
