-- Source Appian CDT: AS_IO_AuditEvent
-- Description: status change event line audit for a record in IO namespace
DROP TABLE IF EXISTS AS_IO_AUDIT_EVENT CASCADE;
CREATE TABLE AS_IO_AUDIT_EVENT (
    AUDIT_EVENT_ID INT PRIMARY KEY,
    RECORD_TYPE_ID VARCHAR(255),
    RECORD_ID VARCHAR(255),
    STATUS_CODE VARCHAR(255),
    COMPLETED_BY VARCHAR(255),
    COMPLETED_ON TIMESTAMP
);
