-- Source Appian CDT: AS_IO_RC_Comment
-- Description: Record Comment CDT
DROP TABLE IF EXISTS AS_IO_RC_COMMENT CASCADE;
CREATE TABLE AS_IO_RC_COMMENT (
    COMMENT_ID INT PRIMARY KEY,
    COMMENT_PARENT_ID INT,
    comment VARCHAR(255),
    SENTIMENT DOUBLE PRECISION,
    recordId VARCHAR(255),
    recordTypeId VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    createdBy VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    modifiedBy VARCHAR(255),
    IS_DELETED BOOLEAN,
    COMMENT_TYPE VARCHAR(255)
);
