-- Source Appian CDT: AS_IO_R_TaskRef
-- Description: Reference task which can be referenced in templates
DROP TABLE IF EXISTS AS_IO_R_TASK_REF CASCADE;
CREATE TABLE AS_IO_R_TASK_REF (
    TASK_REF_ID INT PRIMARY KEY,
    TASK_NAME VARCHAR(255),
    TASK_BEHAVIOR_TYPE_ID INT,
    TASK_CATEGORY_ID INT,
    DEFAULT_GROUP_ASSIGNEE INT,
    TASK_REF_DOC_UPLOAD_ID INT,
    DOC_SIGNATURE_CONTEXT_REF_ID INT,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
