-- Source Appian CDT: AS_IO_A_R_TemplateTask_Precedent
-- Description: Holds auditing data for `AS_IO_R_TemplateTask_Precedent`
DROP TABLE IF EXISTS AS_IO_A_R_TEMPLATE_TASK_PREC CASCADE;
CREATE TABLE AS_IO_A_R_TEMPLATE_TASK_PREC (
    TEMPLATE_TASK_PREC_AUDIT_ID INT PRIMARY KEY,
    TEMPLATE_TASK_AUDIT_ID INT,
    TEMPLATE_TASK_PRECEDENT_ID INT,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
