-- Source Appian CDT: AS_IO_OnboardingDocument_ValidationRule
-- Description: Validation rule that is executed on the document
DROP TABLE IF EXISTS AS_IO_ONBOARDING_DOC_VAL_RULE CASCADE;
CREATE TABLE AS_IO_ONBOARDING_DOC_VAL_RULE (
    VALIDATION_RULE_ID INT PRIMARY KEY,
    ONBOARDING_DOCUMENT_ID INT,
    RULE_ID INT,
    RULE_TYPE VARCHAR(255),
    OUTCOME VARCHAR(255),
    MESSAGE VARCHAR(255),
    OUTPUT VARCHAR(255),
    EXECUTED_DATETIME TIMESTAMP
);
