-- Source Appian CDT: AS_IO_A_R_TaskCategory
-- Description: Holds auditing data for `AS_IO_R_TaskCategory`
DROP TABLE IF EXISTS AS_IO_A_R_TASK_CATEGORY CASCADE;
CREATE TABLE AS_IO_A_R_TASK_CATEGORY (
    TASK_CATEGORY_AUDIT_ID INT PRIMARY KEY,
    TASK_CATEGORY_ID INT,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
