-- Source Appian CDT: AS_IO_RequiredOnboardingDocument
-- Description: Data type for a required document for an onboarding.
DROP TABLE IF EXISTS AS_IO_REQUIRED_ONBOARDING_DOC CASCADE;
CREATE TABLE AS_IO_REQUIRED_ONBOARDING_DOC (
    REQUIRED_ONBOARDING_DOCUMENT_ID INT PRIMARY KEY,
    REQUEST_ID INT,
    DOC_TYPE_CODE VARCHAR(255),
    REQUIREMENT_NAME VARCHAR(255),
    ONBOARDING_DOCUMENT_ID INT,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    IS_DELETED BOOLEAN
);
