-- Source Appian CDT: AS_IO_A_R_TaskRef
-- Description: Holds auditing data for `AS_IO_R_TaskRef`
DROP TABLE IF EXISTS AS_IO_A_R_TASK_REF CASCADE;
CREATE TABLE AS_IO_A_R_TASK_REF (
    TASK_REF_AUDIT_ID INT PRIMARY KEY,
    TASK_REF_ID INT,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
