-- Source Appian CDT: AS_IO_Account_P
-- Description: Parent CDT for the Account Record -- This nests AS_IO_Product_C, AS_IO_Term, and AS_IO_Country (list) and points to the AS_IO_ACCOUNT table - isParent will be equal to true when this is called

For mo
DROP TABLE IF EXISTS AS_IO_ACCOUNT CASCADE;
CREATE TABLE AS_IO_ACCOUNT (
    ACCOUNT_ID INT PRIMARY KEY,
    REQUEST_ID INT,
    CUSTOMER_ID INT,
    FUND_ID INT,
    NAME VARCHAR(255),
    TYPE VARCHAR(255),
    STATUS VARCHAR(255),
    ACCOUNT_NUMBER VARCHAR(255),
    OWNER VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    STRATEGY VARCHAR(255),
    ENTITY VARCHAR(255),
    ENTITY_TYPE VARCHAR(255),
    EST_FUNDING_DATE DATE,
    EST_FUNDING_VALUE DOUBLE PRECISION,
    EST_VALUE_CURRENCY_CODE VARCHAR(255),
    ACTUAL_FUNDING_DATE DATE,
    ACTUAL_FUNDING_VALUE DOUBLE PRECISION,
    ACTUAL_VALUE_CURRENCY_CODE VARCHAR(255),
    TERM_ID INT,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    IS_PARENT BOOLEAN,
    IS_DELETED BOOLEAN
);
