-- Source Appian CDT: AS_IO_A_T_AccountTypeProductTypeMapping_Field
-- Description: Holds auditing data for `AS_IO_T_OnboardingAccountTypeProductTypeMapping` - simple field change
DROP TABLE IF EXISTS AS_IO_A_T_ACCOUNT_TYPE_PRODUCT_TYPE_MAPPING_FIELD CASCADE;
CREATE TABLE AS_IO_A_T_ACCOUNT_TYPE_PRODUCT_TYPE_MAPPING_FIELD (
    ONBOARDING_ACCOUNT_TYPE_PRODUCT_TYPE_MAPPING_AUDIT_FIELD_ID INT PRIMARY KEY,
    ONBOARDING_ACCOUNT_TYPE_PRODUCT_TYPE_MAPPING_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
