-- Source Appian CDT: AS_IO_R_TaskCategory
-- Description: Reference data table for a task category
DROP TABLE IF EXISTS AS_IO_R_TASK_CATEGORY CASCADE;
CREATE TABLE AS_IO_R_TASK_CATEGORY (
    TASK_CATEGORY_ID INT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    IS_ACTIVE BOOLEAN
);
