-- Source Appian CDT: AS_IO_OnboardingRequest
-- Description: Data type for the attributes related to the onboarding request 

For more information see: https://docs.appian.com/suite/help/20.1/io/modifying-record-fields.html
DROP TABLE IF EXISTS AS_IO_ONBOARDING_REQUEST CASCADE;
CREATE TABLE AS_IO_ONBOARDING_REQUEST (
    REQUEST_ID INT PRIMARY KEY,
    UNIQUE_IDENTIFIER VARCHAR(255),
    STATUS VARCHAR(255),
    TYPE VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    CANCEL_REASON VARCHAR(255),
    FOR_NEW_CLIENT BOOLEAN,
    PRIORITY_CODE VARCHAR(255),
    TEMPLATE_ID INT,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP,
    IS_DELETED BOOLEAN,
    SLA_DAY_TYPE VARCHAR(255),
    CUSTOMER_ID INT,
    OWNER_ID INT,
    FUNDING_DETAILS_ID INT
);
