-- Source Appian CDT: AS_IO_A_T_AccountTypeProductTypeMapping
-- Description: Holds auditing data for `AS_IO_T_OnboardingAccountTypeProductTypeMapping`
DROP TABLE IF EXISTS AS_IO_A_T_ACCOUNT_TYPE_PRODUCT_TYPE_MAPPING CASCADE;
CREATE TABLE AS_IO_A_T_ACCOUNT_TYPE_PRODUCT_TYPE_MAPPING (
    ONBOARDING_ACCOUNT_TYPE_PRODUCT_TYPE_MAPPING_AUDIT_ID INT PRIMARY KEY,
    ONBOARDING_ACCOUNT_TYPE_PRODUCT_TYPE_MAPPING_ID INT,
    ONBOARDING_PRODUCT_TEMPLATE_AUDIT_ID INT,
    AUDIT_ACTION_CODE VARCHAR(255),
    USERNAME VARCHAR(255),
    TIMESTAMP TIMESTAMP
);
