-- Source Appian CDT: AS_QNM_A_T_ResponseRequirement
-- Description: Holds auditing data for `AS_QNM_T_ResponseRequirement`
DROP TABLE IF EXISTS AS_QNM_A_T_RESPONSE_REQUIREMENT CASCADE;
CREATE TABLE AS_QNM_A_T_RESPONSE_REQUIREMENT (
    RESPONSE_REQ_TEMPLATE_AUDIT_ID INT PRIMARY KEY,
    RESPONSE_REQUIREMENT_TEMPLATE_ID INT,
    TIMESTAMP TIMESTAMP,
    RECORD_ID INT,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
