-- Source Appian CDT: AS_QNM_A_Response_Field
-- Description: Holds simple field auditing data for `AS_QNM_Response`
DROP TABLE IF EXISTS AS_QNM_A_RESPONSE_FIELD CASCADE;
CREATE TABLE AS_QNM_A_RESPONSE_FIELD (
    RESPONSE_AUDIT_FIELD_ID INT PRIMARY KEY,
    RESPONSE_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
