-- Source Appian CDT: AS_QNM_T_Question
-- Description: Datatype for storing questions on templates
DROP TABLE IF EXISTS AS_QNM_T_QUESTION CASCADE;
CREATE TABLE AS_QNM_T_QUESTION (
    QUESTION_TEMPLATE_ID INT PRIMARY KEY,
    QUESTION_REFERENCE_ID INT,
    QUESTION_TYPE_CODE VARCHAR(255),
    LABEL VARCHAR(255),
    INSTRUCTIONS VARCHAR(255),
    PAGE_NUMBER INT,
    GROUP_NUMBER INT,
    ORDER_NUMBER INT,
    IS_EXTERNAL_USER_FACING BOOLEAN,
    QUESTION_CATEGORY_TEMPLATE_ID INT,
    IS_ACTIVE BOOLEAN,
    created_by VARCHAR(255),
    created_datetime TIMESTAMP,
    modified_by VARCHAR(255),
    modified_datetime TIMESTAMP,
    QUESTIONNAIRE_TEMPLATE_ID INT
);
