-- Source Appian CDT: AS_QNM_R_Response
-- Description: Datatype for indicating a default response/response options in reference questions
DROP TABLE IF EXISTS AS_QNM_R_RESPONSE CASCADE;
CREATE TABLE AS_QNM_R_RESPONSE (
    RESPONSE_REFERENCE_ID INT PRIMARY KEY,
    FIELD_KEY VARCHAR(255),
    LABEL VARCHAR(255),
    VALUE VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
