-- Source Appian CDT: AS_QNM_A_T_QuestionPrecedentSet
-- Description: Holds auditing data for `AS_QNM_T_QuestionPrecedentSet`
DROP TABLE IF EXISTS AS_QNM_A_T_QUESTION_PRECEDENT_SET CASCADE;
CREATE TABLE AS_QNM_A_T_QUESTION_PRECEDENT_SET (
    QUESTION_PRECEDENT_SET_AUDIT_ID INT PRIMARY KEY,
    QUESTION_PRECEDENT_SET_TEMPLATE_ID INT,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
