-- Source Appian CDT: AS_QNM_T_ResponseRequirement
-- Description: Datatype for indicating response requirements for a template question.
DROP TABLE IF EXISTS AS_QNM_T_RSPNS_REQUIREMENT CASCADE;
CREATE TABLE AS_QNM_T_RSPNS_REQUIREMENT (
    RESPONSE_REQUIREMENT_TMPLT_ID INT PRIMARY KEY,
    FIELD_KEY VARCHAR(255),
    REQUIREMENT_TYPE_CODE VARCHAR(255),
    REQUIREMENT_VALUE VARCHAR(255)
);
