-- Source Appian CDT: AS_QNM_T_Questionnaire
-- Description: Datatype for questionnaire templates
DROP TABLE IF EXISTS AS_QNM_T_QUESTIONNAIRE CASCADE;
CREATE TABLE AS_QNM_T_QUESTIONNAIRE (
    QUESTIONNAIRE_TEMPLATE_ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    CUSTOMER_DOMICILE VARCHAR(255),
    CUSTOMER_TYPE_CODE VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
