-- Source Appian CDT: AS_QNM_A_T_Question_Field
-- Description: Holds auditing data for `AS_QNM_T_Question` - simple field change
DROP TABLE IF EXISTS AS_QNM_A_T_QUESTION_FIELD CASCADE;
CREATE TABLE AS_QNM_A_T_QUESTION_FIELD (
    QUESTION_TEMPLATE_AUDIT_FIELD_ID INT PRIMARY KEY,
    QUESTION_TEMPLATE_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
