-- Source Appian CDT: AS_QNM_A_Questionnaire
-- Description: Holds auditing data for the `AS_QNM_Questionnaire` CDT
DROP TABLE IF EXISTS AS_QNM_A_QUESTIONNAIRE CASCADE;
CREATE TABLE AS_QNM_A_QUESTIONNAIRE (
    QUESTIONNAIRE_AUDIT_ID INT PRIMARY KEY,
    QUESTIONNAIRE_ID INT,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
