-- Source Appian CDT: AS_QNM_ResponseRequirement
-- Description: Datatype for indicating response requirements for a question.
DROP TABLE IF EXISTS AS_QNM_RSPNS_REQUIREMENT CASCADE;
CREATE TABLE AS_QNM_RSPNS_REQUIREMENT (
    RESPONSE_REQUIREMENT_ID INT PRIMARY KEY,
    FIELD_KEY VARCHAR(255),
    REQUIREMENT_TYPE_CODE VARCHAR(255),
    REQUIREMENT_VALUE VARCHAR(255)
);
