-- Source Appian CDT: AS_QNM_R_ResponseRequirement
-- Description: Datatype for indicating response requirements for a reference question.
DROP TABLE IF EXISTS AS_QNM_R_RSPNS_REQUIREMENT CASCADE;
CREATE TABLE AS_QNM_R_RSPNS_REQUIREMENT (
    RESPONSE_REQUIREMENT_REF_ID INT PRIMARY KEY,
    FIELD_KEY VARCHAR(255),
    REQUIREMENT_TYPE_CODE VARCHAR(255),
    REQUIREMENT_VALUE VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATETIME TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    MODIFIED_DATETIME TIMESTAMP
);
