-- Source Appian CDT: AS_QNM_A_Questionnaire_Field
-- Description: Holds simple field auditing data for `AS_QNM_Questionnaire`
DROP TABLE IF EXISTS AS_QNM_A_QUESTIONNAIRE_FIELD CASCADE;
CREATE TABLE AS_QNM_A_QUESTIONNAIRE_FIELD (
    QUESTIONNAIRE_AUDIT_FIELD_ID INT PRIMARY KEY,
    QUESTIONNAIRE_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
