-- Source Appian CDT: AS_QNM_A_Question
-- Description: Holds auditing data for the `AS_QNM_Question` CDT
DROP TABLE IF EXISTS AS_QNM_A_QUESTION CASCADE;
CREATE TABLE AS_QNM_A_QUESTION (
    QUESTION_AUDIT_ID INT PRIMARY KEY,
    QUESTION_ID INT,
    TIMESTAMP TIMESTAMP,
    RECORD_ID INT,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
