-- Source Appian CDT: AS_QNM_A_Question_Field
-- Description: Holds simple field auditing data for `AS_QNM_Question`
DROP TABLE IF EXISTS AS_QNM_A_QUESTION_FIELD CASCADE;
CREATE TABLE AS_QNM_A_QUESTION_FIELD (
    QUESTION_AUDIT_FIELD_ID INT PRIMARY KEY,
    QUESTION_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
