-- Source Appian CDT: AS_QNM_A_Response
-- Description: Holds auditing data for the `AS_QNM_Response` CDT
DROP TABLE IF EXISTS AS_QNM_A_RESPONSE CASCADE;
CREATE TABLE AS_QNM_A_RESPONSE (
    RESPONSE_AUDIT_ID INT PRIMARY KEY,
    RESPONSE_ID INT,
    TIMESTAMP TIMESTAMP,
    RECORD_ID INT,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
