-- Source Appian CDT: AS_QNM_A_T_QuestionPrecedent_Field
-- Description: Holds auditing data for `AS_QNM_T_QuestionPrecedent` - simple field change
DROP TABLE IF EXISTS AS_QNM_A_T_QUESTION_PRECEDENT_FIELD CASCADE;
CREATE TABLE AS_QNM_A_T_QUESTION_PRECEDENT_FIELD (
    QUESTION_PRECEDENT_AUDIT_FIELD_ID INT PRIMARY KEY,
    QUESTION_PRECEDENT_AUDIT_ID INT,
    FIELD_NAME VARCHAR(255),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255)
);
