-- Source Appian CDT: AS_QNM_A_T_Response
-- Description: Holds auditing data for `AS_QNM_T_Response`
DROP TABLE IF EXISTS AS_QNM_A_T_RESPONSE CASCADE;
CREATE TABLE AS_QNM_A_T_RESPONSE (
    RESPONSE_TEMPLATE_AUDIT_ID INT PRIMARY KEY,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
