-- Source Appian CDT: AS_QNM_A_T_QuestionPrecedent
-- Description: Holds auditing data for `AS_QNM_T_QuestionPrecedent`
DROP TABLE IF EXISTS AS_QNM_A_T_QUESTION_PRECEDENT CASCADE;
CREATE TABLE AS_QNM_A_T_QUESTION_PRECEDENT (
    QUESTION_PRECEDENT_AUDIT_ID INT PRIMARY KEY,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    RECORD_ID INT,
    AUDIT_ACTION_CODE VARCHAR(255)
);
