-- Source Appian CDT: AS_QNM_A_T_QuestionCategory
-- Description: Holds auditing data for `AS_QNM_T_QuestionCategory`
DROP TABLE IF EXISTS AS_QNM_A_T_QUESTION_CATEGORY CASCADE;
CREATE TABLE AS_QNM_A_T_QUESTION_CATEGORY (
    QUESTION_CATEGORY_TEMPLATE_AUDIT_ID INT PRIMARY KEY,
    QUESTION_CATEGORY_TEMPLATE_ID INT,
    TIMESTAMP TIMESTAMP,
    RECORD_ID INT,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
