-- Source Appian CDT: AS_QNM_Question
-- Description: Datatype for representing questions
DROP TABLE IF EXISTS AS_QNM_QUESTION CASCADE;
CREATE TABLE AS_QNM_QUESTION (
    QUESTION_ID INT PRIMARY KEY,
    QUESTION_REFERENCE_ID INT,
    QUESTION_TEMPLATE_ID INT,
    LABEL VARCHAR(255),
    INSTRUCTIONS VARCHAR(255),
    PAGE_NUMBER INT,
    GROUP_NUMBER INT,
    ORDER_NUMBER INT,
    IS_EXTERNAL_USER_FACING BOOLEAN,
    QUESTION_CATEGORY_ID INT,
    QUESTION_TYPE_CODE VARCHAR(255)
);
