-- Source Appian CDT: AS_QNM_A_T_Question
-- Description: Holds auditing data for `AS_QNM_T_Question`
DROP TABLE IF EXISTS AS_QNM_A_T_QUESTION CASCADE;
CREATE TABLE AS_QNM_A_T_QUESTION (
    QUESTION_TEMPLATE_AUDIT_ID INT PRIMARY KEY,
    QUESTION_TEMPLATE_ID INT,
    RECORD_ID INT,
    TIMESTAMP TIMESTAMP,
    USERNAME VARCHAR(255),
    AUDIT_ACTION_CODE VARCHAR(255)
);
